trailingComma: "es5"
tabWidth: 2
semi: false
singleQuote: true
printWidth: 80
useTabs: false
quoteProps: consistent
jsxSingleQuote: true
bracketSpacing: true
bracketSameLine: true
arrowParens: always
parser: typescript
embeddedLanguageFormatting: "auto"
singleAttributePerLine: true
