export const textSizesXS = 'text-xs md:text-sm lg:text-base '
export const textSizesSM = 'text-sm md:text-base lg:text-lg '
export const textSizesBASE = 'text-base md:text-lg lg:text-xl '
export const textSizesLG = 'text-lg md:text-xl lg:text-2xl '
export const textSizesXL = 'text-xl md:text-2xl lg:text-3xl '
export const textSizes2XL = 'text-2xl md:text-3xl lg:text-4xl '
export const textSizes3XL = 'text-3xl md:text-4xl lg:text-5xl '
export const textSizes4XL = 'text-4xl md:text-5xl lg:text-6xl '
export const textSizes5XL = 'text-5xl md:text-6xl lg:text-7xl '
export const textSizes6XL = 'text-6xl md:text-7xl lg:text-8xl '
export const textSizes7XL = 'text-7xl md:text-8xl lg:text-9xl '
export const linkStyle = 'text-ctp-blue hover:text-ctp-sapphire '


export const textSizesXS2 = 'text-sm lg:text-base '
export const textSizesSM2 = 'text-base lg:text-lg '
export const textSizesBASE2 = 'text-lg lg:text-xl '
export const textSizesLG2 = 'text-xl lg:text-2xl '
export const textSizesXL2 = 'text-2xl lg:text-3xl '
export const textSizes2XL2 = 'text-3xl lg:text-4xl '
export const textSizes3XL2 = 'text-4xl lg:text-5xl '
export const textSizes4XL2 = 'text-5xl lg:text-6xl '
export const textSizes5XL2 = 'text-6xl lg:text-7xl '
export const textSizes6XL2 = 'text-7xl lg:text-8xl '
export const textSizes7XL2 = 'text-8xl lg:text-9xl '
